name: Build iis-shortname-scanner image 

on: 
  workflow_dispatch:
  workflow_call:

jobs:
  build_iis-shortname-scanner:
    runs-on: ubuntu-latest
    steps:
      - name: checkout 
        uses: actions/checkout@v3
        
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      
      - name: Build and push iis-shortname-scanner image
        uses: docker/build-push-action@v3
        with:
          context: Tools/iis-shortname-scanner/
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/iis-shortname-scanner:latest
